development:
  database:
    host: 0.0.0.0
    port: 5454
    user: order
    password: order
    dbname: db-order
  http:
    host: 0.0.0.0
    port: 8080
production:
  database:
    host: 10.10.0.1
    port: 5453
    user: order
    password: order
    dbname: db_order
  http:
    host: 0.0.0.0
    port: 8084
