order-redis:
    image: redis
    volumes:
        - ./data/redis/data:/data
    ports:
        - "6379:6379"
    entrypoint: redis-server

order-mongo:
  image: mongo
  log_driver: 'json-file'
  log_opt:
    max-size: '10MB'
    max-file: '2'
  ports:
    - "28017:27017"
  volumes:
    - ./data/mongo/data:/data

order-postgresql:
  restart: always
  image: postgres
  ports:
    - "5454:5432"
  environment:
    - POSTGRES_DB=db-order
    - POSTGRES_PASSWORD=order
    - POSTGRES_USER=order
  volumes:
    - ./postgresql/data:/var/lib/postgresql/data
